# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "spec/rails_helper.rb"
